### ISSUE TITLE
entering portal in nether does not teleport you and causes this error

### ISSUE THREAD

**Issue by rustyshakelford2** [ferrybig/multiworld#16]
`[19:36:39] [Server thread/ERROR]: Could not pass event PlayerPortalEvent to MultiWorld v5.2.8
java.lang.IllegalArgumentException: Cannot use null location!
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.event.player.PlayerMoveEvent.validateLocation(PlayerMoveEvent.java:95) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.event.player.PlayerMoveEvent.setTo(PlayerMoveEvent.java:90) ~[patched_1.13.2.jar:git-Paper-624]
	at multiworld.addons.NetherPortalHandler.onPlayerPortal(NetherPortalHandler.java:41) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor192.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-624]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.PlayerList.changeDimension(PlayerList.java:807) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.EntityPlayer.a(EntityPlayer.java:753) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.Entity.postTick(Entity.java:382) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1563) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.World.g(World.java:1529) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.WorldServer.p_(WorldServer.java:622) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1306) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:599) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1107) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]`

**Comment by rustyshakelford2** [comment]
Update: Confirmed this is still an issue on the pre-alpha version you posted 

`[19:45:18] [Server thread/ERROR]: Could not pass event PlayerPortalEvent to MultiWorld v5.3.0-BETA
java.lang.IllegalArgumentException: Cannot use null location!
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.event.player.PlayerMoveEvent.validateLocation(PlayerMoveEvent.java:95) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.event.player.PlayerMoveEvent.setTo(PlayerMoveEvent.java:90) ~[patched_1.13.2.jar:git-Paper-624]
	at multiworld.addons.NetherPortalHandler.onPlayerPortal(NetherPortalHandler.java:41) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor192.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-624]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.PlayerList.changeDimension(PlayerList.java:807) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.EntityPlayer.a(EntityPlayer.java:753) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.Entity.postTick(Entity.java:382) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1563) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.World.g(World.java:1529) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.WorldServer.p_(WorldServer.java:622) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1306) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:599) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1107) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]`
